# Generated by Django 3.2.9 on 2021-11-26 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0002_materias'),
    ]

    operations = [
        migrations.AddField(
            model_name='listado',
            name='age',
            field=models.BigIntegerField(null=True),
        ),
    ]
