# Generated by Django 3.2.9 on 2021-11-27 01:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0003_listado_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='calificaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.DecimalField(decimal_places=2, max_digits=2)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.listado')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.materias')),
            ],
        ),
    ]
