# Generated by Django 3.2.9 on 2021-11-27 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0004_calificaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='materias',
            name='maestro',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
